In [1]:
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
type(iris)

sklearn.utils.Bunch

In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
x = iris.data
y = iris.target
x.shape, y.shape, type(x), type(y)

((150, 4), (150,), numpy.ndarray, numpy.ndarray)

In [5]:
import numpy as np
np.unique(y)

array([0, 1, 2])

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test =train_test_split(x, y)
# 순서 매우 중요하니 기억 ㄱㄱ
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((112, 4), (38, 4), (112,), (38,))

In [7]:
from sklearn.linear_model import LogisticRegression
log=LogisticRegression()

In [8]:
log.fit(x_train, y_train)

c:\python\python36\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [9]:
log.coef_, log.intercept_

(array([[-0.42993313,  0.87270542, -2.34595649, -0.99151182],
        [ 0.499395  , -0.24626959, -0.20274485, -0.79909631],
        [-0.06946187, -0.62643583,  2.54870134,  1.79060813]]),
 array([  9.43229097,   1.9111492 , -11.34344016]))

y= -0.45654027x + 0.80872888x + -2.33625808x + -0.95465147x + 9.75127935

In [10]:
log.predict_proba(x_train[100:104])

array([[1.15392865e-04, 2.10688123e-01, 7.89196484e-01],
       [6.34445656e-04, 4.65336044e-01, 5.34029510e-01],
       [9.47079543e-01, 5.29198263e-02, 6.31139572e-07],
       [1.04427427e-05, 6.89285519e-02, 9.31061005e-01]])

In [11]:
log.predict(x_train[100:104])

array([2, 2, 0, 2])

In [12]:
4.40646974e-05+7.12042198e-02+9.28751715e-01

0.9999999994973999

In [13]:
from sklearn import metrics

In [14]:
y_pred = log.predict(x_train)
y_pred.shape, y_train.shape

((112,), (112,))

In [15]:
y_pred

array([2, 1, 0, 0, 1, 1, 1, 0, 0, 0, 2, 1, 1, 2, 1, 2, 0, 2, 1, 0, 0, 0,
       2, 0, 2, 0, 2, 2, 1, 2, 2, 1, 0, 2, 1, 2, 1, 0, 0, 1, 0, 1, 2, 0,
       1, 0, 0, 0, 2, 0, 2, 0, 2, 1, 2, 1, 1, 2, 2, 1, 0, 1, 1, 0, 1, 1,
       2, 2, 0, 1, 0, 1, 1, 2, 2, 2, 0, 2, 1, 2, 2, 2, 2, 2, 0, 2, 0, 2,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 2, 2, 0, 2, 2, 1, 1, 2, 1, 0,
       0, 0])

In [16]:
y_train

array([2, 1, 0, 0, 1, 1, 1, 0, 0, 0, 2, 1, 1, 2, 1, 2, 0, 2, 1, 0, 0, 0,
       2, 0, 2, 0, 2, 2, 1, 2, 2, 1, 0, 2, 1, 2, 1, 0, 0, 1, 0, 1, 2, 0,
       1, 0, 0, 0, 2, 0, 2, 0, 2, 1, 2, 1, 1, 2, 2, 1, 0, 1, 1, 0, 1, 1,
       2, 2, 0, 1, 0, 1, 1, 1, 2, 2, 0, 2, 1, 1, 2, 2, 2, 2, 0, 2, 0, 2,
       2, 1, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 2, 2, 0, 2, 2, 1, 1, 2, 1, 0,
       0, 0])

In [17]:
print(metrics.classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        34
           1       0.97      0.95      0.96        40
           2       0.95      0.97      0.96        38

    accuracy                           0.97       112
   macro avg       0.97      0.97      0.97       112
weighted avg       0.97      0.97      0.97       112



In [18]:
metrics.confusion_matrix(y_train, y_pred)

array([[34,  0,  0],
       [ 0, 38,  2],
       [ 0,  1, 37]], dtype=int64)