In [1]:
from sklearn import datasets

In [3]:
iris = datasets.load_iris()
type(iris)

sklearn.utils.Bunch

In [4]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [15]:
x = iris.data
y = iris.target
x.shape, y.shape, type(x), type(y)

((150, 4), (150,), numpy.ndarray, numpy.ndarray)

In [16]:
import numpy as np
np.unique(y)

array([0, 1, 2])

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test =train_test_split(x, y)
# 순서 매우 중요하니 기억 ㄱㄱ
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((112, 4), (38, 4), (112,), (38,))

In [18]:
from sklearn.linear_model import LogisticRegression
log=LogisticRegression()

In [19]:
log.fit(x_train, y_train)

c:\python\python36\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [20]:
log.coef_, log.intercept_

(array([[-0.45654027,  0.80872888, -2.33625808, -0.95465147],
        [ 0.47136412, -0.37698658, -0.20756839, -0.86119435],
        [-0.01482385, -0.4317423 ,  2.54382646,  1.81584582]]),
 array([  9.75127935,   2.48227098, -12.23355033]))

y= -0.45654027x + 0.80872888x + -2.33625808x + -0.95465147x + 9.75127935

In [25]:
log.predict_proba(x_train[100:104])

array([[4.40646974e-05, 7.12042198e-02, 9.28751715e-01],
       [9.81731765e-01, 1.82681916e-02, 4.30426339e-08],
       [1.54530656e-07, 5.45434496e-03, 9.94545501e-01],
       [9.84429440e-01, 1.55705316e-02, 2.78942991e-08]])

In [22]:
log.predict(x_train[100:104])

array([2, 0, 2, 0])

In [23]:
4.40646974e-05+7.12042198e-02+9.28751715e-01

0.9999999994973999

In [26]:
from sklearn import metrics

In [28]:
y_pred = log.predict(x_train)
y_pred.shape, y_train.shape

((112,), (112,))

In [29]:
y_pred

array([1, 2, 2, 2, 1, 1, 2, 1, 1, 2, 0, 0, 0, 2, 0, 1, 2, 2, 1, 0, 0, 1,
       2, 2, 0, 2, 1, 0, 1, 2, 2, 1, 1, 1, 0, 0, 1, 0, 1, 0, 2, 1, 2, 2,
       2, 2, 0, 1, 2, 1, 1, 2, 1, 1, 0, 2, 2, 0, 1, 0, 0, 2, 1, 1, 1, 1,
       2, 1, 1, 2, 1, 0, 2, 0, 1, 1, 1, 0, 2, 0, 0, 2, 0, 2, 0, 2, 1, 2,
       0, 1, 1, 2, 0, 2, 1, 2, 0, 0, 0, 2, 2, 0, 2, 0, 2, 0, 2, 1, 2, 0,
       2, 1])

In [30]:
y_train

array([1, 2, 2, 1, 1, 1, 2, 1, 1, 2, 0, 0, 0, 2, 0, 1, 2, 2, 1, 0, 0, 1,
       2, 2, 0, 2, 1, 0, 1, 2, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 2, 2, 2, 2,
       2, 2, 0, 1, 2, 1, 1, 2, 1, 1, 0, 2, 2, 0, 1, 0, 0, 2, 1, 1, 1, 1,
       2, 1, 1, 2, 1, 0, 2, 0, 1, 1, 1, 0, 2, 0, 0, 2, 0, 2, 0, 2, 1, 2,
       0, 1, 1, 2, 0, 2, 1, 2, 0, 0, 0, 2, 2, 0, 2, 0, 2, 0, 2, 1, 2, 0,
       2, 1])

In [33]:
print(metrics.classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        33
           1       0.97      0.95      0.96        39
           2       0.95      0.97      0.96        40

    accuracy                           0.97       112
   macro avg       0.97      0.97      0.97       112
weighted avg       0.97      0.97      0.97       112



In [ ]:
metrics.confusion_matrix()